[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "plutopus-telemetry"
version = "0.1.0"
description = "Telemetry ingestion service for Plutopus"
requires-python = ">=3.12"
dependencies = [
    "kafka-python-ng>=2.2.2",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "pydantic>=2.0.0",
    "plutopus-schemas",
    "plutopus-shared"
]

[tool.setuptools.packages.find]
where = ["src"]
