[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "plutopus-api"
version = "0.1.0"
description = "FastAPI backend for Plutopus"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "pydantic-settings>=2.2.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "alembic>=1.13.0",
    "networkx>=3.0",
    "PyJWT>=2.8.0",
    "prometheus-client>=0.19.0",
    "plutopus-schemas",
    "plutopus-shared"
]

[tool.setuptools.packages.find]
where = ["src"]
